import discord
import random
import json
import asyncio
import uuid

from datetime import datetime
from discord import app_commands
from discord.ext import commands
from discord.app_commands import Choice

with open('./config.json') as cjson:
    config = json.load(cjson)

def keygenerator(string_length=5):
    random = str(uuid.uuid4())
    random = random.upper()
    random = random.replace("-", "")
    return random[0:string_length]

class keygen(commands.Cog):
    def __init__(self, bot: commands.Bot) -> None:
        self.bot = bot

    @app_commands.command(
        name="genkey",
        description="Generate Keys")
    
    @app_commands.describe(
        type="Select the Type of Key you want to generate",
    )
    @app_commands.choices(type=[
        app_commands.Choice(name="Day", value="day"),
        app_commands.Choice(name="Week", value="week"),
        app_commands.Choice(name="Month", value="month"),
        app_commands.Choice(name="Lifetime", value="lifetime")
        ])
    
    async def genkey(self, interaction: discord.Interaction, type: app_commands.Choice[str]) -> None:


        if interaction.user.id == config["BotOwner"]:
            if type.value == "day":
                key = keygenerator(5) + "-" + keygenerator(5) + "-" + keygenerator(5) + "-" + keygenerator(5)

                #The Success Message
                gembed = discord.Embed(title="",
                              description=f"Your {type.name} key was succesfully generated, saved and sent to your DMs",
                              color=0xfffb00)
                gembed.set_author(name="Key Generated", icon_url=config["IconURL"])
                gembed.set_footer(text=f"generated by {interaction.user.name}", icon_url=interaction.user.avatar.url)
                gembed.timestamp = datetime.utcnow()

                #The DM Message with the code
                dmembed = discord.Embed(title="",
                                description=f"Your generated code is ||{key}|| 🔑\n Keep the code secret! 🤫",
                                color=0xfffb00)
                dmembed.set_footer(text="generatet at: ", icon_url=config["IconURL"])

                with open("day_keys.txt", "w") as df:
                    df.writelines(key + "\n")
                    df.close()
                await interaction.response.send_message(interaction.user.mention, embed=gembed)
                await interaction.user.send(embed=dmembed)

        else:
            #The Error Message
            errorembed = discord.Embed(title="",
                                   description="You dont have enough permissions to run this command!",
                                   color=0xfffb00)
            errorembed.set_author(name="Error", icon_url=config["IconURL"])
            errorembed.set_footer(text=interaction.user.name, icon_url=interaction.user.avatar.url)
            await interaction.response.send_message(interaction.user.mention, embed=errorembed)

        


async def setup(bot: commands.Bot) -> None:
    await bot.add_cog(
        keygen(bot),
        guilds=[discord.Object(config["GuildID"])]
    )